version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ID-ECR.ecr.eu-west-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=14.2_$COMMIT_HASH
      - IMAGE_URI="ID-ECR.dkr.ecr.eu-west-1.amazonaws.com/name-of-the-project:${IMAGE_TAG}"
      - LATEST_IMAGE_URI="ID-ECR.dkr.ecr.eu-west-1.amazonaws.com/name-of-the-project:latest"
  build:
    commands:
      - aws s3 cp s3://bucket-with-the-env/.env .env
      - docker build -t "$IMAGE_URI" .
      - docker tag "$IMAGE_URI" "$LATEST_IMAGE_URI"
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - docker push "$LATEST_IMAGE_URI"
      - printf '[{"name":"%s","imageUri":"%s"}]' "www-name" "$IMAGE_URI" > images.json
artifacts:
  files: images.json
